import {
  ArrowRight,
  Award,
  Briefcase,
  Calendar,
  Camera,
  ChefHat,
  Coins,
  FileText,
  Gem,
  Globe,
  Heart,
  HeartHandshake,
  Lightbulb,
  Mail,
  MapPin,
  Medal,
  Music,
  Phone,
  Presentation,
  Rocket,
  Shield,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Store,
  Target,
  Ticket,
  TrendingUp,
  Trophy,
  Users,
  type LucideIcon,
} from "lucide-react";

export const eventsIconMap: Record<string, LucideIcon> = {
  IconAward: Award,
  IconArrowRight: ArrowRight,
  IconBriefcase: Briefcase,
  IconBuildingStore: Store,
  IconBulb: Lightbulb,
  IconCalendar: Calendar,
  IconCamera: Camera,
  IconCoin: Coins,
  IconFileText: FileText,
  IconHeart: Heart,
  IconHeartHandshake: HeartHandshake,
  IconMusic: Music,
  IconRibbon: Medal,
  IconRings: Gem,
  IconRocket: Rocket,
  IconShieldCheck: ShieldCheck,
  IconSparkles: Sparkles,
  IconStar: Star,
  IconTarget: Target,
  IconTrendingUp: TrendingUp,
  IconTrophy: Trophy,
  IconUsers: Users,
  IconWorld: Globe,
  Award,
  Calendar,
  ChefHat,
  Heart,
  MapPin,
  Music,
  Presentation,
  Shield,
  Smile,
  Sparkles,
  Ticket,
  Users,
  delivery: Rocket,
  email: Mail,
  location: MapPin,
  phone: Phone,
  send: ArrowRight,
  shield: Shield,
  support: HeartHandshake,
  users: Users,
  verified: ShieldCheck,
};

export const renderEventsIcon = (
  iconName: string | undefined,
  className: string,
  fallback: LucideIcon = Sparkles,
) => {
  const IconComp = (iconName && eventsIconMap[iconName]) || fallback;
  return <IconComp className={className} aria-hidden />;
};
