"use client";

import type { ComponentType, SVGProps } from "react";
import {
  FiActivity,
  FiArrowRight,
  FiArrowUpRight,
  FiAward,
  FiBook,
  FiBookOpen,
  FiBriefcase,
  FiCheck,
  FiCheckCircle,
  FiClock,
  FiDollarSign,
  FiDownload,
  FiDroplet,
  FiEye,
  FiFeather,
  FiGift,
  FiGlobe,
  FiHeart,
  FiHome,
  FiMail,
  FiMapPin,
  FiPhone,
  FiSettings,
  FiShield,
  FiSmile,
  FiStar,
  FiTarget,
  FiTrendingUp,
  FiUser,
  FiUserCheck,
  FiUsers,
  FiHeadphones,
  FiSend,
  FiThumbsUp,
} from "react-icons/fi";
import {
  FaChalkboardTeacher,
  FaFacebookF,
  FaGift,
  FaHandHoldingHeart,
  FaHandshake,
  FaInstagram,
  FaLinkedinIn,
  FaPinterestP,
  FaUsers,
  FaYoutube,
} from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { BsAwardFill } from "react-icons/bs";
import { RiGraduationCapFill, RiInstagramFill } from "react-icons/ri";
import {
  LuActivity,
  LuGraduationCap,
  LuLeaf,
  LuPawPrint,
  LuSmile,
} from "react-icons/lu";
import {
  HiOutlineBuildingOffice2,
  HiOutlineMegaphone,
  HiOutlineSparkles,
  HiOutlineUserGroup,
} from "react-icons/hi2";
import {
  IoShieldCheckmarkOutline,
  IoStatsChartOutline,
  IoWaterOutline,
} from "react-icons/io5";
import {
  Building2,
  Globe,
  Handshake,
  Headphones,
  HeartHandshake,
  Mail,
  MapPin,
  Phone,
  ShieldCheck,
  Target,
  ThumbsUp,
  Users,
} from "lucide-react";

type NgoIconComponent = ComponentType<SVGProps<SVGSVGElement> & { className?: string }>;

/** Shared NGO icon registry — same pattern as Events `eventsIcons`. */
export const ngoIconMap: Record<string, NgoIconComponent> = {
  heart: FiHeart,
  donation: FiHeart,
  "heart-hand": FaHandHoldingHeart,
  "hands-heart": FaHandHoldingHeart,
  "hand-holding-heart": FaHandHoldingHeart,
  "heart-hands": HeartHandshake as NgoIconComponent,
  healthcare: LuActivity,
  "heart-pulse": LuActivity,
  "activity-heartbeat": LuActivity,
  medical: LuActivity,
  education: FiBookOpen,
  book: FiBookOpen,
  "book-open": FiBookOpen,
  "file-text": FiBook,
  download: FiDownload,
  "graduation-cap": LuGraduationCap,
  users: FiUsers,
  people: FaUsers,
  "people-group": HiOutlineUserGroup,
  community: FiUsers,
  women: FiUsers,
  empowerment: FiUsers,
  "user-female": FiUser,
  children: LuSmile,
  child: LuSmile,
  check: FiCheck,
  star: FiStar,
  award: FiAward,
  ribbon: BsAwardFill,
  trophy: FiAward,
  shield: FiShield,
  "shield-check": IoShieldCheckmarkOutline,
  "shield-check-outline": IoShieldCheckmarkOutline,
  target: FiTarget,
  handshake: FaHandshake,
  "handshake-outline": FaHandshake,
  water: FiDroplet,
  drop: FiDroplet,
  "water-drop": IoWaterOutline,
  globe: FiGlobe,
  gift: FiGift,
  megaphone: HiOutlineMegaphone,
  "bowl-hot": FiHome,
  "food-bowl": FiHome,
  leaf: LuLeaf,
  tree: LuLeaf,
  school: HiOutlineBuildingOffice2,
  "theatre-masks": FiSmile,
  gears: FiSettings,
  "paw-print": LuPawPrint,
  growth: FiTrendingUp,
  chart: FiTrendingUp,
  coin: FiDollarSign,
  clipboard: FiBook,
  document: FiBook,
  training: LuGraduationCap,
  message: FiMail,
  envelope: FiMail,
  user: FiUser,
  edit: FiFeather,
  pencil: FiFeather,
  send: FiSend,
  "paper-plane": FiSend,
  "heart-percentage": IoStatsChartOutline,
  vision: FiEye,
  mission: FiTarget,
  goal: FiCheckCircle,
  helpless: FiHome,
  headset: FiHeadphones,
  "thumbs-up": FiThumbsUp,
  building: HiOutlineBuildingOffice2,
  "map-pin": FiMapPin,
  phone: FiPhone,
  mail: FiMail,
  clock: FiClock,
  arrow: FiArrowRight,
  "arrow-right": FiArrowRight,

  Building2: Building2 as NgoIconComponent,
  Users: Users as NgoIconComponent,
  Handshake: Handshake as NgoIconComponent,
  Target: Target as NgoIconComponent,
  MapPin: MapPin as NgoIconComponent,
  Phone: Phone as NgoIconComponent,
  Mail: Mail as NgoIconComponent,
  Globe: Globe as NgoIconComponent,
  Headphones: Headphones as NgoIconComponent,
  HeartHandshake: HeartHandshake as NgoIconComponent,
  ShieldCheck: ShieldCheck as NgoIconComponent,
  ThumbsUp: ThumbsUp as NgoIconComponent,

  FiActivity,
  FiArrowRight,
  FiArrowUpRight,
  FiAward,
  FiBook,
  FiBookOpen,
  FiBriefcase,
  FiCheck,
  FiCheckCircle,
  FiClock,
  FiDollarSign,
  FiDroplet,
  FiEye,
  FiFeather,
  FiGift,
  FiGlobe,
  FiHeart,
  FiHome,
  FiMail,
  FiMapPin,
  FiPhone,
  FiSettings,
  FiShield,
  FiSmile,
  FiStar,
  FiTarget,
  FiTrendingUp,
  FiUser,
  FiUserCheck,
  FiUsers,
  FiHeadphones,
  FiThumbsUp,
  FiPresentation: FaChalkboardTeacher,
  FiGraduationCap: RiGraduationCapFill,
  FiHeartHandshake: FaHandHoldingHeart,
  FaGift,
  FaUsers,
  BsAwardFill,
  LuActivity,
  LuGraduationCap,
  LuSmile,
};

export const ngoSocialIconMap: Record<string, NgoIconComponent> = {
  facebook: FaFacebookF,
  instagram: FaInstagram,
  twitter: FaXTwitter,
  x: FaXTwitter,
  linkedin: FaLinkedinIn,
  youtube: FaYoutube,
  pinterest: FaPinterestP,
  "instagram-fill": RiInstagramFill,
};

export const ngoSocialIconOptions: Array<{ value: string; label: string }> = [
  { value: "facebook", label: "Facebook" },
  { value: "instagram", label: "Instagram" },
  { value: "twitter", label: "Twitter / X" },
  { value: "linkedin", label: "LinkedIn" },
  { value: "youtube", label: "YouTube" },
  { value: "pinterest", label: "Pinterest" },
];

export const ngoIconOptions: Array<{ value: string; label: string }> = [
  { value: "heart", label: "Heart" },
  { value: "heart-hand", label: "Heart Hand" },
  { value: "healthcare", label: "Healthcare" },
  { value: "education", label: "Education" },
  { value: "book-open", label: "Book Open" },
  { value: "file-text", label: "File" },
  { value: "download", label: "Download" },
  { value: "graduation-cap", label: "Graduation Cap" },
  { value: "users", label: "Users" },
  { value: "people", label: "People" },
  { value: "people-group", label: "People Group" },
  { value: "community", label: "Community" },
  { value: "check", label: "Check" },
  { value: "star", label: "Star" },
  { value: "award", label: "Award" },
  { value: "trophy", label: "Trophy" },
  { value: "ribbon", label: "Ribbon" },
  { value: "shield", label: "Shield" },
  { value: "shield-check", label: "Shield Check" },
  { value: "target", label: "Target" },
  { value: "handshake", label: "Handshake" },
  { value: "water", label: "Water" },
  { value: "water-drop", label: "Water Drop" },
  { value: "globe", label: "Globe" },
  { value: "gift", label: "Gift" },
  { value: "megaphone", label: "Megaphone" },
  { value: "leaf", label: "Leaf" },
  { value: "tree", label: "Tree" },
  { value: "school", label: "School" },
  { value: "theatre-masks", label: "Theatre Masks" },
  { value: "gears", label: "Gears" },
  { value: "paw-print", label: "Paw Print" },
  { value: "food-bowl", label: "Food Bowl" },
  { value: "user-female", label: "User" },
  { value: "activity-heartbeat", label: "Heartbeat" },
  { value: "hands-heart", label: "Hands Heart" },
  { value: "heart-hands", label: "Heart Hands" },
  { value: "handshake-outline", label: "Handshake Outline" },
  { value: "growth", label: "Growth" },
  { value: "mission", label: "Mission" },
  { value: "vision", label: "Vision" },
  { value: "goal", label: "Goal" },
  { value: "helpless", label: "Shelter / Home" },
  { value: "headset", label: "Headset" },
  { value: "thumbs-up", label: "Thumbs Up" },
  { value: "building", label: "Building" },
  { value: "map-pin", label: "Map Pin" },
  { value: "phone", label: "Phone" },
  { value: "mail", label: "Mail" },
  { value: "envelope", label: "Envelope" },
  { value: "user", label: "User" },
  { value: "edit", label: "Edit" },
  { value: "send", label: "Send" },
  { value: "paper-plane", label: "Paper Plane" },
  { value: "clock", label: "Clock" },
  { value: "women", label: "Women / Empowerment" },
  { value: "arrow-right", label: "Arrow Right" },
  { value: "FiUsers", label: "Users" },
  { value: "FiBookOpen", label: "Book Open" },
  { value: "FiAward", label: "Award" },
  { value: "FiShield", label: "Shield" },
  { value: "FiStar", label: "Star" },
  { value: "FiTarget", label: "Target" },
  { value: "FiTrendingUp", label: "Trending Up" },
  { value: "FiHome", label: "Home" },
  { value: "FiSmile", label: "Smile" },
  { value: "FiGift", label: "Gift" },
  { value: "FiGlobe", label: "Globe" },
  { value: "FiBook", label: "Book" },
  { value: "FiUser", label: "User" },
  { value: "FiFeather", label: "Feather" },
  { value: "FiPresentation", label: "Presentation" },
  { value: "FiUserCheck", label: "User Check" },
  { value: "FiClock", label: "Clock" },
  { value: "FiBriefcase", label: "Briefcase" },
];

const resolveIcon = (
  map: Record<string, NgoIconComponent>,
  iconName: string | undefined,
  fallback: NgoIconComponent,
): NgoIconComponent => {
  if (!iconName) return fallback;
  const trimmed = iconName.trim();
  if (map[trimmed]) return map[trimmed];
  const lower = trimmed.toLowerCase();
  if (map[lower]) return map[lower];
  return fallback;
};

export const renderNgoIcon = (
  iconName: string | undefined,
  className = "h-5 w-5",
  fallback: NgoIconComponent = HiOutlineSparkles,
) => {
  const IconComp = resolveIcon(ngoIconMap, iconName, fallback);
  return <IconComp className={className} aria-hidden />;
};

export const renderNgoSocialIcon = (
  iconName: string | undefined,
  className = "h-4 w-4",
  fallback: NgoIconComponent = FaFacebookF,
) => {
  const IconComp = resolveIcon(ngoSocialIconMap, iconName, fallback);
  return <IconComp className={className} aria-hidden />;
};
